import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import type { RootState } from "../index";

// ─── Types ────────────────────────────────────────────────────────────────────

export type StockStatus = "in-stock" | "low-stock" | "out-of-stock";

export interface BoutiqueCategory {
  id: string;
  name: string;
  prefix: string;       // e.g. "PRN", "BND" — used for SKU generation
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface BoutiqueProduct {
  id: string;
  sku: string;           // auto-generated by backend, e.g. PRN-001
  name: string;
  description: string;
  categoryId: string;
  category: BoutiqueCategory;
  unit: string;          // e.g. "per 100", "per item"
  price: number;
  stock: number;
  minStock: number;
  status: StockStatus;   // computed by backend
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface StockMovement {
  id: string;
  productId: string;
  change: number;        // positive = restock, negative = sale/use
  reason: string;
  changedBy: {
    id: string;
    name: string;
  };
  createdAt: string;
}

// ─── Request / Response shapes ────────────────────────────────────────────────

export interface GetProductsParams {
  categoryId?: string;
  status?: StockStatus;
  search?: string;
  page?: number;
  limit?: number;
}

export interface PaginatedProducts {
  products: BoutiqueProduct[];
  pagination: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}

export interface CreateCategoryPayload {
  name: string;
  prefix: string;
}

export interface UpdateCategoryPayload {
  id: string;
  name?: string;
  prefix?: string;
}

export interface CreateProductPayload {
  name: string;
  description: string;
  categoryId: string;
  unit: string;
  price: number;
  stock: number;
  minStock: number;
}

export interface UpdateProductPayload {
  id: string;
  name?: string;
  description?: string;
  categoryId?: string;
  unit?: string;
  price?: number;
  minStock?: number;
}

export interface UpdateStockPayload {
  id: string;
  change: number;   // positive = restock, negative = sale/use
  reason: string;
}

interface ApiResponse<T> {
  success: boolean;
  message: string;
  data: T;
  pagination?: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}

// ─── Service ──────────────────────────────────────────────────────────────────

export const boutiqueApi = createApi({
  reducerPath: "boutiqueApi",

  baseQuery: fetchBaseQuery({
    baseUrl: `${import.meta.env.VITE_API_URL ?? "http://localhost:8000/api"}/boutique`,
    prepareHeaders: (headers, { getState }) => {
      const token = (getState() as RootState).auth.token;
      if (token) headers.set("Authorization", `Bearer ${token}`);
      return headers;
    },
  }),

  tagTypes: ["BoutiqueCategory", "BoutiqueProduct", "StockMovement"],

  endpoints: (builder) => ({

    // ── Categories ────────────────────────────────────────────────────────────

    // GET /boutique/categories
    getCategories: builder.query<BoutiqueCategory[], void>({
      query: () => "/categories",
      transformResponse: (res: ApiResponse<BoutiqueCategory[]>) => res.data,
      providesTags: (result) =>
        result
          ? [
              ...result.map(({ id }) => ({ type: "BoutiqueCategory" as const, id })),
              { type: "BoutiqueCategory", id: "LIST" },
            ]
          : [{ type: "BoutiqueCategory", id: "LIST" }],
    }),

    // POST /boutique/categories — ADMIN only
    createCategory: builder.mutation<BoutiqueCategory, CreateCategoryPayload>({
      query: (body) => ({ url: "/categories", method: "POST", body }),
      transformResponse: (res: ApiResponse<BoutiqueCategory>) => res.data,
      invalidatesTags: [{ type: "BoutiqueCategory", id: "LIST" }],
    }),

    // PUT /boutique/categories/:id — ADMIN only
    updateCategory: builder.mutation<BoutiqueCategory, UpdateCategoryPayload>({
      query: ({ id, ...body }) => ({ url: `/categories/${id}`, method: "PUT", body }),
      transformResponse: (res: ApiResponse<BoutiqueCategory>) => res.data,
      invalidatesTags: (_r, _e, { id }) => [
        { type: "BoutiqueCategory", id },
        { type: "BoutiqueCategory", id: "LIST" },
      ],
    }),

    // DELETE /boutique/categories/:id — ADMIN only (soft delete)
    deleteCategory: builder.mutation<void, string>({
      query: (id) => ({ url: `/categories/${id}`, method: "DELETE" }),
      invalidatesTags: (_r, _e, id) => [
        { type: "BoutiqueCategory", id },
        { type: "BoutiqueCategory", id: "LIST" },
      ],
    }),

    // ── Products ──────────────────────────────────────────────────────────────

    // GET /boutique/products?categoryId=&status=&search=&page=&limit=
    getProducts: builder.query<PaginatedProducts, GetProductsParams | void>({
      query: (params) => ({
        url: "/products",
        // default limit=100 so we get all products in one shot for the boutique view
        params: { limit: 100, ...(params ?? {}) } as Record<string, unknown>,
      }),
      transformResponse: (res: ApiResponse<BoutiqueProduct[]>) => ({
        products: res.data ?? [],
        pagination: res.pagination ?? {
          total: res.data?.length ?? 0,
          page: 1,
          limit: 100,
          totalPages: 1,
        },
      }),
      providesTags: (result) =>
        result?.products
          ? [
              ...result.products.map(({ id }) => ({ type: "BoutiqueProduct" as const, id })),
              { type: "BoutiqueProduct", id: "LIST" },
            ]
          : [{ type: "BoutiqueProduct", id: "LIST" }],
    }),

    // GET /boutique/products/:id
    getProductById: builder.query<BoutiqueProduct, string>({
      query: (id) => `/products/${id}`,
      transformResponse: (res: ApiResponse<BoutiqueProduct>) => res.data,
      providesTags: (_r, _e, id) => [{ type: "BoutiqueProduct", id }],
    }),

    // POST /boutique/products — ADMIN, STOCK
    createProduct: builder.mutation<BoutiqueProduct, CreateProductPayload>({
      query: (body) => ({ url: "/products", method: "POST", body }),
      transformResponse: (res: ApiResponse<BoutiqueProduct>) => res.data,
      invalidatesTags: [{ type: "BoutiqueProduct", id: "LIST" }],
    }),

    // PUT /boutique/products/:id — ADMIN, STOCK
    updateProduct: builder.mutation<BoutiqueProduct, UpdateProductPayload>({
      query: ({ id, ...body }) => ({ url: `/products/${id}`, method: "PUT", body }),
      transformResponse: (res: ApiResponse<BoutiqueProduct>) => res.data,
      invalidatesTags: (_r, _e, { id }) => [
        { type: "BoutiqueProduct", id },
        { type: "BoutiqueProduct", id: "LIST" },
      ],
    }),

    // DELETE /boutique/products/:id — ADMIN only (soft delete)
    deleteProduct: builder.mutation<void, string>({
      query: (id) => ({ url: `/products/${id}`, method: "DELETE" }),
      invalidatesTags: (_r, _e, id) => [
        { type: "BoutiqueProduct", id },
        { type: "BoutiqueProduct", id: "LIST" },
      ],
    }),

    // ── Stock ─────────────────────────────────────────────────────────────────

    // PATCH /boutique/products/:id/stock — ADMIN, STOCK
    updateStock: builder.mutation<BoutiqueProduct, UpdateStockPayload>({
      query: ({ id, ...body }) => ({
        url: `/products/${id}/stock`,
        method: "PATCH",
        body,
      }),
      transformResponse: (res: ApiResponse<BoutiqueProduct>) => res.data,
      invalidatesTags: (_r, _e, { id }) => [
        { type: "BoutiqueProduct", id },
        { type: "BoutiqueProduct", id: "LIST" },
        { type: "StockMovement", id },
      ],
    }),

    // GET /boutique/products/:id/stock-movements
    getStockMovements: builder.query<StockMovement[], string>({
      query: (id) => `/products/${id}/stock-movements`,
      transformResponse: (res: ApiResponse<StockMovement[]>) => res.data,
      providesTags: (_r, _e, id) => [{ type: "StockMovement", id }],
    }),
  }),
});

export const {
  useGetCategoriesQuery,
  useCreateCategoryMutation,
  useUpdateCategoryMutation,
  useDeleteCategoryMutation,
  useGetProductsQuery,
  useGetProductByIdQuery,
  useCreateProductMutation,
  useUpdateProductMutation,
  useDeleteProductMutation,
  useUpdateStockMutation,
  useGetStockMovementsQuery,
} = boutiqueApi;
